---
# The YAML header specifies several settings for the survey but is not required.
# A full list of settings can be found under _survey/settings.yml directory.

theme-settings:
  theme: default
  barposition: top
  footer-left: "Made with [surveydown](https://surveydown.org)"
  footer-right: '[<i class="bi bi-github"></i> Source Code](https://github.com/surveydown-dev/template_custom_plotly_chart)'

survey-settings:
  show-previous: false
  use-cookies: false
  auto-scroll: false
  rate-survey: false
  system-language: en
  highlight-unanswered: true
  highlight-color: blue
  capture-metadata: true
  all-questions-required: false
  required-questions:
    - point_selection
---

```{r}
library(surveydown)
```

--- plotly_chart

# Template - Custom Plotly Chart

```{r}
#| out.width: "100%"

sd_output("point_selection", type = "question")
```

### You selected: `r sd_output("point_selection", type = "value")`

--- end

## End

This it the last page in the survey.

```{r}
sd_close()
```
